
import { FoodItem } from '@/src/types/food';

// Helper profiles based on the Venezuelan Exchange List for 1 Ration
const MACROS = {
  MUY_BAJA_GRASA: { proteins_g: 8, lipids_g: 1.2, carbs_g: 12, fiber_g: 0, calories: 90 },
  BAJA_GRASA: { proteins_g: 8, lipids_g: 2.4, carbs_g: 12, fiber_g: 0, calories: 102 },
  SEMIDESCREMADA: { proteins_g: 8, lipids_g: 4.8, carbs_g: 12, fiber_g: 0, calories: 123 },
  ENTERA: { proteins_g: 8, lipids_g: 8.0, carbs_g: 12, fiber_g: 0, calories: 150 },
};

export const dairyDatabase: FoodItem[] = [
  // --- BAJA EN GRASA (1%) ---
  {
    id: 'leche-descremada-1',
    name: 'Leche descremada 1%',
    categoryId: 'dairy',
    subCategoryId: 'baja_grasa',
    measure: '1 taza (8 onzas)',
    amount_g_ml: 240,
    unit: 'cc',
    ...MACROS.BAJA_GRASA,
    micros: { calcium_mg: 300 } // ADA placeholder example
  },
  {
    id: 'yogurt-frutas-descremado',
    name: 'Yogurt con frutas descremado (sin azúcar)',
    categoryId: 'dairy',
    subCategoryId: 'baja_grasa',
    measure: '1 taza (8 onzas)',
    amount_g_ml: 240,
    unit: 'g',
    ...MACROS.BAJA_GRASA,
  },
  {
    id: 'leche-descremada-polvo',
    name: 'Leche descremada 1% en polvo',
    categoryId: 'dairy',
    subCategoryId: 'baja_grasa',
    measure: '4 cucharadas',
    amount_g_ml: 32,
    unit: 'g',
    ...MACROS.BAJA_GRASA,
  },
  {
    id: 'leche-evaporada-descremada',
    name: 'Leche evaporada descremada',
    categoryId: 'dairy',
    subCategoryId: 'baja_grasa',
    measure: '1/2 taza (4 onzas)',
    amount_g_ml: 120,
    unit: 'cc',
    ...MACROS.BAJA_GRASA,
  },
  {
    id: 'yogurt-simple-descremado',
    name: 'Yogurt simple descremado (firme)',
    categoryId: 'dairy',
    subCategoryId: 'baja_grasa',
    measure: '3/4 taza',
    amount_g_ml: 180,
    unit: 'g',
    ...MACROS.BAJA_GRASA,
  },

  // --- SEMIDESCREMADA (2%) ---
  {
    id: 'leche-semidescremada-2',
    name: 'Leche semidescremada al 2%',
    categoryId: 'dairy',
    subCategoryId: 'semidescremada',
    measure: '1 taza (8 onzas)',
    amount_g_ml: 240,
    unit: 'cc',
    ...MACROS.SEMIDESCREMADA,
  },
  {
    id: 'leche-acidificada',
    name: 'Leche acidificada',
    categoryId: 'dairy',
    subCategoryId: 'semidescremada',
    measure: '1 taza (8 onzas)',
    amount_g_ml: 240,
    unit: 'cc',
    ...MACROS.SEMIDESCREMADA,
  },
  {
    id: 'leche-semidescremada-polvo',
    name: 'Leche semidescremada en polvo al 2%',
    categoryId: 'dairy',
    subCategoryId: 'semidescremada',
    measure: '4 cucharadas',
    amount_g_ml: 32,
    unit: 'g',
    ...MACROS.SEMIDESCREMADA,
  },
  {
    id: 'yogurt-liquido-semi',
    name: 'Yogurt líquido semidescremado c/ frutas',
    categoryId: 'dairy',
    subCategoryId: 'semidescremada',
    measure: '3/4 taza',
    amount_g_ml: 180,
    unit: 'cc',
    ...MACROS.SEMIDESCREMADA,
  },

  // --- ENTERA ---
  {
    id: 'kefir',
    name: 'Kéfir',
    categoryId: 'dairy',
    subCategoryId: 'entera',
    measure: '1 taza (8 onzas)',
    amount_g_ml: 240,
    unit: 'cc',
    ...MACROS.ENTERA,
  },
  {
    id: 'leche-entera',
    name: 'Leche entera',
    categoryId: 'dairy',
    subCategoryId: 'entera',
    measure: '1 taza (8 onzas)',
    amount_g_ml: 240,
    unit: 'cc',
    ...MACROS.ENTERA,
  },
  {
    id: 'leche-cabra',
    name: 'Leche de cabra',
    categoryId: 'dairy',
    subCategoryId: 'entera',
    measure: '1 taza (8 onzas)',
    amount_g_ml: 240,
    unit: 'cc',
    ...MACROS.ENTERA,
  },
  {
    id: 'suero-leche',
    name: 'Suero de leche',
    categoryId: 'dairy',
    subCategoryId: 'entera',
    measure: '1 taza (8 onzas)',
    amount_g_ml: 240,
    unit: 'cc',
    ...MACROS.ENTERA,
  },
  {
    id: 'leche-entera-polvo',
    name: 'Leche entera en polvo',
    categoryId: 'dairy',
    subCategoryId: 'entera',
    measure: '4 cucharadas',
    amount_g_ml: 32,
    unit: 'g',
    ...MACROS.ENTERA,
  },
  {
    id: 'leche-evaporada',
    name: 'Leche evaporada',
    categoryId: 'dairy',
    subCategoryId: 'entera',
    measure: '1/2 taza (4 onzas)',
    amount_g_ml: 120,
    unit: 'cc',
    ...MACROS.ENTERA,
  },

  // --- DESLACTOSADOS ---
  // *Note: Using Semidescremada macros as a placeholder for these. 
  // Adjust to Entera or Baja en Grasa if the specific clinical table dictates otherwise.
  {
    id: 'leche-deslactosada',
    name: 'Leche deslactosada',
    categoryId: 'dairy',
    subCategoryId: 'deslactosada',
    measure: '1 taza (8 onzas)',
    amount_g_ml: 240,
    unit: 'cc',
    ...MACROS.SEMIDESCREMADA, 
  },
  {
    id: 'yogurt-deslactosado',
    name: 'Yogurt deslactosado',
    categoryId: 'dairy',
    subCategoryId: 'deslactosada',
    measure: '3/4 taza',
    amount_g_ml: 180,
    unit: 'g',
    ...MACROS.SEMIDESCREMADA,
  },
];